name: blip-bot-monitoring

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  dotnet:
    secrets: inherit
    uses: stilingue-inteligencia-artificial/github-actions/.github/workflows/dotnet.yml@v0
    with:
      project-type: lib
      tags: |
        team:scalability
        product:blip-brain
        squad:ai-scalability
        application-group:blip-brain
        type:api
        owner:staff
        system:ai-scalability
        criticality:medium
        classification:confidential
        product-cycle:alpha