name: blip-bot-monitoring

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  dotnet:
    secrets: inherit
    uses: stilingue-inteligencia-artificial/github-actions/.github/workflows/dotnet.yml@main
    with:
      project-type: lib
      tags: |
        team:research-development
        squad:ai-scalability
        application-group:blip
        owner:chapter-lead
        criticality:medium
        classification:confidential
        product-cycle:alpha
        system:blip-ai